# map parameter registry
map_param_registry = {
    "3m_3m": {
        "n_agents": 3,
        "n_enemies": 3,
        "limit": 60,
        "a_race": "T",
        "b_race": "T",
        "unit_type_bits": 0,
        "map_type": 'marines'},
    "5m_5m": {
        "n_agents": 5,
        "n_enemies": 5,
        "limit": 60,
        "a_race": "T",
        "b_race": "T",
        "unit_type_bits": 0,
        "map_type": 'marines'},
    "8m_8m": {
        "n_agents": 8,
        "n_enemies": 8,
        "limit": 120,
        "a_race": "T",
        "b_race": "T",
        "unit_type_bits": 0,
        "map_type": 'marines'},
    "MMM": {
        "n_agents": 10,
        "n_enemies": 10,
        "limit": 150,
        "a_race": "T",
        "b_race":"T",
        "unit_type_bits": 3,
        "map_type": 'MMM'},
    "2s_3z": {
        "n_agents": 5,
        "n_enemies": 5,
        "limit": 120,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 2,
        "map_type": 'sz'},
    "3s_5z": {
        "n_agents": 8,
        "n_enemies": 8,
        "limit": 150,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 2,
        "map_type": 'sz'},
    "1c_3s_5z": {
        "n_agents": 9,
        "n_enemies": 9,
        "limit": 200,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 3,
        "map_type": 'csz'},
    "2c_3s_5z": {
        "n_agents": 10,
        "n_enemies": 10,
        "limit": 200,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 3,
        "map_type": 'csz'},
    "3s_vs_3z": {
        "n_agents": 3,
        "n_enemies": 3,
        "limit": 120,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 0,
        "map_type": 's_v_z'},
    "3s_vs_4z": {
        "n_agents": 3,
        "n_enemies": 4,
        "limit": 120,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 0,
        "map_type": 's_v_z'},
    "3s_vs_5z": {
        "n_agents": 3,
        "n_enemies": 5,
        "limit": 150,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 0,
        "map_type": 's_v_z'},
    "3s_vs_6z": {
        "n_agents": 3,
        "n_enemies": 6,
        "limit": 150,
        "a_race": "P",
        "b_race": "P",
        "unit_type_bits": 0,
        "map_type": 's_v_z'},
    "micro1": {
        "n_agents": 2,
        "n_enemies": 1,
        "limit": 150,
        "a_race": "T",
        "b_race": "P",
        "unit_type_bits": 0,
        "map_type": 'm_z'},
    }

def get_map_params(map_name):
    return map_param_registry[map_name]

def map_present(map_name):
    return map_name in map_param_registry
